version: '3'
services: 
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: yarn dev
    volumes: 
      - '.:/usr/src/app'

  serve:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: node build/server.js
    volumes: 
      - '.:/usr/src/app'
